[build-system]
requires      = ["setuptools>=65", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dibisoplot"
dynamic = ["version"]
description = "A Python library for plotting bibliometric research data, developed at the DiBISO."
readme = "README.md"
authors = [{ name = "Romain Thomas", email = "contact@romainthomas.net" }]
license = "GPL-3.0-only"
license-files = [
    "LICENSE.txt"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Visualization",
    "Typing :: Typed"
]
keywords = ["DiBISO", "Data analysis", "Scientific research", "Plotly"]
dependencies = [
    "numpy >= 1.21.5",
    "pandas >= 2.0.1",
    "plotly >= 6.3.1",
    "tqdm >= 4.65.0",
    "requests",
    "emoji-country-flag",
    "openalex-analysis >= 0.15",
    "elasticsearch>7,<9",
    "pylatexenc",
    "pyalex"
]
requires-python = ">=3.10"

[tool.setuptools]
packages = ["dibisoplot", "dibisoplot.biso"]

[tool.setuptools.dynamic]
version = { attr = "dibisoplot._version.__version__" }

[tool.setuptools.package-data]
myModule = ["dibisoplot/biso/HAL_doc_types_names.toml"]

[project.urls]
Homepage = "https://pypi.org/project/dibisoplot/"
Repository = "https://github.com/dibiso-upsaclay/dibisoplot"
Documentation = "https://dibiso-upsaclay.github.io/dibisoplot/"
DOI = "https://doi.org/10.5281/zenodo.17251536"
